### ISSUE TITLE
Atualizar README com informações do projeto

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#1]
Atualmente essas informações estão com os valores padrão do template. Arrumar para que reflitam informações reais.

**Comment by estelavilasboas** [comment]
Estou utilizando como base o READ ME do site de Ciência da Computação. Retirei as partes sobre contribuições, mas esse READ ME também possui uma parte sobre *dúvidas gerais*. Para onde devem ser direcionadas essas dúvidas? Para os coordenadores ou para o e-mail do programa? Ou deveríamos deixar sem essa parte por enquanto? 


![image](https://user-images.githubusercontent.com/30927758/86812888-e716b680-c055-11ea-9b7f-1ab29fa2c723.png)


Os passos de instalação continuam como o READ ME de Computação e os *links importantes* contêm apenas o site do PRACTICE e o da UFFS. Seria necessário mais algum?


![image](https://user-images.githubusercontent.com/30927758/86813227-45439980-c056-11ea-90fd-1c0bca936559.png)

**Comment by Dovyski** [comment]
Pode informar o e-mail do programa, `practice@uffs.edu.br`, como local para dúvidas gerais, sem mencionar nome de pessoas (alguém responderá o e-mail em nome do programa).
