### ISSUE TITLE
Verificar e ajustar informações no Site do PRACTICE

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/website-programa#101]
[Pagina Portfólio](https://practice.uffs.edu.br/portfolio/)
![image](https://user-images.githubusercontent.com/29258164/138569618-892fd16a-b095-415b-b707-f6f7139d4f8c.png)

- [x] Eliminar "Data" "Pessoas impactadas" e "dsds" (Apenas eliminar mesmo, deixar só o título e a imagem)

---

- [x] Ajustar nome nas equipes:
- de Guilherme Smorcionski Nerling
- para Guilherme Smorcinski Nerling

---

- [x] [Transmissões](https://practice.uffs.edu.br/portfolio/lives/) -> Tenta ver se consegue pegar a informação de "Pessoas Impactadas" direto do link da live no Youtube e do Facebook:
 
![image](https://user-images.githubusercontent.com/51202705/154490165-18a51a3f-b2b1-4740-b05b-d1f8427db576.png)

![image](https://user-images.githubusercontent.com/51202705/154490518-95df836e-6f99-4a0e-a28f-9e1666f08cd0.png)

![image](https://user-images.githubusercontent.com/51202705/154490873-1263b2a5-5d87-4d61-8e76-92c320a8002f.png)

---

- [x] Também ou tentar arrumar as imagens na parte de equipe
![image](https://user-images.githubusercontent.com/49656211/155001745-df4aa3a0-8d81-499a-b2dd-ad858f8cf98a.png)

**Comment by alissonpeloso** [comment]
eaí, @SWE3T, conseguiu rodar o site do practice no localhost?
