### ISSUE TITLE
Adicionar Cartilha "Principais órgãos da UFFS e suas funções"

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/website-programa#105]
'a  cartilha deve ser postada juntamente com os demais materiais de cartilhas. Segue uma pequena descrição para anexar junto: _"O PRACTICE elaborou essa cartilha no intuito de auxiliar os acadêmicos facilitando o acesso às informações relacionadas aos órgãos da UFFS e das funções que cada órgão desenvolve"_. Agradecida ^^'

_Originally posted by @Vandipedrotti in https://github.com/practice-uffs/programa/issues/825#issuecomment-1047140139_

---

Adicionar a cartilha criada pela @Vandipedrotti no site do PRACTICE, na aba de [Recursos](https://practice.uffs.edu.br/recursos/)

**Comment by CleissonVieira** [comment]
Cartilha adicionada ao fonte e ao servidor.
Assim que o código-fonte for atualizado no servidor, o mesmo vai estar disponível para produção
