### ISSUE TITLE
Adicionar Cartilha "cartilha sobre saúde mental dos estudantes" no site do PRACTICE

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/website-programa#106]
> Gostaria de solicitar o auxílio da @practice-uffs/dev para publicação desse material no site do Practice, na aba RECURSOS.
> Título: CARTILHA DE APOIO PARA SAÚDE MENTAL DOS ESTUDANTES
> Descrição: Essa cartilha foi elaborada com atenção especial à vida e saúde do estudante da universidade. Tem objetivo de informar e auxiliar os estudantes de graduação a identificarem possíveis problemas que envolvem sua saúde mental, e saberem como e onde buscar ajuda.
> 
> A cartilha se encontra na pasta de saída dessa issue.

_Originally posted by @brendaellen in https://github.com/practice-uffs/programa/issues/637#issuecomment-1047165269_

---

Da mesma forma como a issue #105, apenas adicionar essa [cartilha](https://drive.google.com/drive/folders/1rG9RTOVEA_0qFRcjsWb8JcBIzKprjA1m) na aba de [recursos](https://practice.uffs.edu.br/recursos/) do Site do PRACTICE

**Comment by CleissonVieira** [comment]
Cartilha adicionada ao fonte e ao servidor.
Assim que o código-fonte for atualizado no servidor, o mesmo vai estar disponível para produção
