### ISSUE TITLE
Alterar logos das aplicações do Practice no website

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/website-programa#109]
Ajustar os logos no site do [PRACTICE]( https://practice.uffs.edu.br/tecnologias/) de acordo com as novas logos dessa [issue](https://github.com/practice-uffs/programa/issues/969)

**Comment by CleissonVieira** [comment]
@alissonpeloso @TaynaraCh 
Os ícones estão fora de padrão. Precisamos ajustar para todos ficarem com o mesmo tamanho no website.
Caso não seja relevante, e prefiram desta forma, informar que em seguida coloco para versão em produção.
Tirei print de forma padrão para identificar os tamanhos. Referência por X, sendo X-2 o menor e X+2 o maior tamanho:


Tamanho X+2:
- Aplicativo da Aura (sem link)

Tamanho X+1:
- [UFFS Virtual](https://drive.google.com/drive/folders/13OQ3qlC0smzQVUp5lD_An_Wcg5yyGxVB)

Tamanho X:
- [APP Bem estar](https://drive.google.com/drive/folders/1nW2YXuP1gMqr_qeEQGNalZyuOWUFssZU)
- [Forms](https://drive.google.com/drive/folders/1YEwKj4_BRf7S_jMzsMVq3OCOVZaZFi9e)
- [Maker](https://drive.google.com/drive/folders/1DKIvIN4LHKdpAzh1pHsqbHFKNOl6jOx6)

Tamanho X-1:
- [Mural](https://drive.google.com/drive/folders/1hGKBrAAI6jMsl_i2l7oH4xi4s8MZPhAE)

Tamanho X-2:
- [APP Boas vindas](https://drive.google.com/drive/folders/1tQwwFmC4RpO6QB7wzpugPjw7ZaRlrNs0)

![image](https://user-images.githubusercontent.com/29258164/156960684-4238adf1-3814-44e9-801b-0959a4c6cbfd.png)
![image](https://user-images.githubusercontent.com/29258164/156960435-4a677759-a86e-4d8b-928a-57643ba97f13.png)
![image](https://user-images.githubusercontent.com/29258164/156960489-cf9f9043-7f28-4135-bd21-c05bb06253f8.png)
![image](https://user-images.githubusercontent.com/29258164/156960528-f669a79a-f266-404c-b047-e13978df532d.png)

**Comment by CleissonVieira** [comment]
Icones atualizados de PNG para SVG, agora padronizados
