### ISSUE TITLE
Atualizar site

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/website-programa#115]
Alterações na aba de equipes do PRACTICE:

- [x] Retirar nome Claudinéia Vieira Raimundi ->A Néia se formou e não é mais membro do PRACTICE.

OBS: lembrar de atualizar histórico também.

- [x] Adicionar a Júlia Zanini- Equipe de mídia

- [x] Adicionar Eduardo F. Dias- Equipe de Design

- [x] Adicionar Saene Viceli- Equipe de design

**Comment by morgana-mo** [comment]
As fotos estão [aqui](https://drive.google.com/drive/folders/1quKDorJEXBU38pnYX4iDIlFINO6-PGXX)

**Comment by morgana-mo** [comment]
@alissonpeloso designar alguém  para essa tarefa

**Comment by CleissonVieira** [comment]
@morgana-mo estou adicionando o Eduardo na equipe de design, porém, informo que na planilha de membros o mesmo está para equipe de mídia, conforme imagem abaixo:
![image](https://user-images.githubusercontent.com/29258164/176320154-36e1dfed-5d37-4ab7-a505-8d065c152118.png)

**Comment by CleissonVieira** [comment]
Membros adicionados ao website
Aguardando servidor atualizar.

![image](https://user-images.githubusercontent.com/29258164/176321628-b7be7d6d-ccbc-4856-8ef6-6e1d854807ec.png)
![image](https://user-images.githubusercontent.com/29258164/176321648-d4abcb96-ec93-4fc0-9e2c-6faf803cdc4a.png)
![image](https://user-images.githubusercontent.com/29258164/176321670-8d5a6576-c130-44ef-9c9c-acd0fb84d988.png)

**Comment by alissonpeloso** [comment]
@morgana-mo e @CleissonVieira, realizei a atualização no servidor. Se acessarem o site pelo firefox (por causa daquele problema de certificado), irão ver as alterações.
