### ISSUE TITLE
Alterações no site

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/website-programa#118]
São necessárias algumas alterações no nosso site:

- [x] Adicionar : Elisangela Ribas dos Santos-Coordenadora
- [x] Remover:Maurício Fernando Bozatski
- [x] Remover:Fernando Bevilacqua
- [x] Alterar:Cleisson Vieira Raimundi para voluntário
- [x] Alterar:Júlia Gaboardi Bodanese para a equipe de Auxílio Gerencial
P.S: Lembrar de alterar as "barras" pretas do final do site.

**Comment by morgana-mo** [comment]
@alissonpeloso como commentado na reunião de hoje de manhã estão as alterações do site

**Comment by lcaimi** [comment]
Deve-se ajustar também a aba com o histórico de participação destas pessoas.

**Comment by alissonpeloso** [comment]
Histórico aqui: https://practice.uffs.edu.br/equipe/historico/

**Comment by alissonpeloso** [comment]
Atualizações realizadas, aguardando revisão.

**Comment by morgana-mo** [comment]
Histórico conferido e `Ok`,  vi que no site ainda não ocorreu a alteração das pessoas na aba Quem somos?

**Comment by alissonpeloso** [comment]
> Histórico conferido e `Ok`, vi que no site ainda não ocorreu a alteração das pessoas na aba Quem somos?

PR ainda em revisão [aqui](https://github.com/practice-uffs/website-programa/pull/121), assim que for aceito irei atualizar o site.

**Comment by alissonpeloso** [comment]
Atualizado no site
