### ISSUE TITLE
Postar notícias no site

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/website-programa#125]
Postar as 4 notícias do link abaixo no site:

[Pasta com o texto](https://drive.google.com/drive/folders/1plaXXuszl_-vMr_RdhacDmDgT5UGl8rg)

**Comment by morgana-mo** [comment]
@alissonpeloso assim que possível essa tarefa deve ser executada

**Comment by morgana-mo** [comment]
Imagens de capa disponíveis [aqui](https://drive.google.com/drive/folders/14k8I8hLuGFORkm1WCXNinrJkkm0u2Shj)

**Comment by marconiryan** [comment]
### Alguma idéia de titulo ou ta bom assim?
[![USOdOX.png](https://iili.io/USOdOX.png)](https://freeimage.host/)
[![USOJRt.png](https://iili.io/USOJRt.png)](https://freeimage.host/)
[![USOHJI.png](https://iili.io/USOHJI.png)](https://freeimage.host/)
[![USNtWJ.png](https://iili.io/USNtWJ.png)](https://freeimage.host/)
