### ISSUE TITLE
Arrumar a coluna ultimas notícias dentro de uma notícia.

### ISSUE THREAD

**Issue by marconiryan** [practice-uffs/website-programa#126]
Quando você entra em alguma noticia, tem uma coluna de "Últimas notícias" no canto direito. Acontece que essa coluna ocupa praticamente o site inteiro e não é possivel ver ou acessar as ultimas noticiais.

**Comment by marconiryan** [comment]
[![USadNI.md.png](https://iili.io/USadNI.md.png)](https://freeimage.host/i/USadNI)

**Comment by alissonpeloso** [comment]
Faltou adicionar o Project "Geral", colocar no estado de "fazer" e selecionar a sprint atual para a issue @marconiryan
