### ISSUE TITLE
Postar Guia do estudante no site

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/website-programa#139]
@zorteaadriano 
Postar Guia do estudante no site , ele está[ nessa pasta ](https://drive.google.com/drive/folders/1KZtEM0vt0VqjcscfGAudB3WA80o9tFBh)

**Comment by brendaellen** [comment]
Inseri na pasta de [saída](https://drive.google.com/drive/folders/1KZtEM0vt0VqjcscfGAudB3WA80o9tFBh) a descrição que deve ser colocada no site, junto ao guia.

**Comment by Saene99** [comment]
Precisei fazer algumas alterações no guia. Acabei de alterar o material da pasta.

**Comment by Saene99** [comment]
@zorteaadriano quando o guia for postado, pode comentar aqui, por gentileza? Apenas para sabermos quando divulgar nas redes sociais :)

@amandasegattob irá gravar como encontrar no site

**Comment by zorteaadriano** [comment]
@Saene99 pronto, tive que corrigir umas coisinhas e levei um tempo a mais, mas agora está ok!

Acessível através da página recursos ou pelo link:
https://practice.uffs.edu.br/Guia-do-Estudante/
