### ISSUE TITLE
Atualizar /equipe para conter mais infos dos membros

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#14]
Atualizar a página equipe para conter o seguinte:

* Para membros da gerência: titulação (ex.: Doutor em Computação) e cargo na UFFS (Professor de Ciência da Computação)
* Para membros da equipe: curso (ex.: Acadêmica de Ciência da Computação)

Para todos, colocar link para o perfil no github (usando um ícone do Github ao lado).

**Comment by phdmauricio** [comment]
@CleissonVieira Adicionar os servidores de Laranajeiras na equipe/ alterar "professores" por "servidores"...

**Comment by CleissonVieira** [comment]
> @CleissonVieira Adicionar os servidores de Laranajeiras na equipe/ alterar "professores" por "servidores"...

Quem são esses servidores? Preciso da informação deles.
