### ISSUE TITLE
Criar página /servico/midia

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#15]
Essa página deve conter informações sobre os serviços de audio e vídeo. Enquanto as informações não forem disponibilizadas pela equipe responsável, colocar algum texto genérico.

**Comment by CleissonVieira** [comment]
@practice-uffs/con-midia Aguardo novas informações para acrescentar na [página](https://practice.uffs.cc/servico/midia/).

**Comment by phdmauricio** [comment]
Estamos trabalhando no fluxo de pedido dos clientes. Creio que até terça-feira estaremos com tudo finalizado.

**Comment by CleissonVieira** [comment]
@phdmauricio 
Alguma novidade do que colocar na página do site de [áudio e vídeo](https://practice.uffs.cc/servico/midia/) até dia 29 para lançamento do programa?

**Comment by phdmauricio** [comment]
Sim, estou trabalhando no texto, teremos 3 novidades. Projeto Além da Fronteira; Projeto do Livro Didático Digital e o estúdio montado no campus chapecó. Vou elaborar os textos.
