### ISSUE TITLE
Criar página /servico/conteudo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#16]
Essa página deve conter informações sobre os serviços de conteúdo. Enquanto as informações não forem disponibilizadas pela equipe responsável, colocar algum texto genérico.

**Comment by CleissonVieira** [comment]
@practice-uffs/con-material  Aguardo novas informações para acrescentar na página.

**Comment by CleissonVieira** [comment]
@practice-uffs/con-material 
Alguma novidade do que colocar na página do site de [texto e imagem](https://practice.uffs.cc/servico/conteudo/) até dia 29 para lançamento do programa?
