### ISSUE TITLE
Criar página /servico/evento-virtual

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#17]
Essa página deve conter informações sobre os serviços de auxílio em eventos virtuais. No texto, deve ficar muito claro que tipo de evento nós auxiliamos (no momento, apenas semanas acadêmicas).

Enquanto as informações não forem disponibilizadas pela equipe responsável, colocar algum texto genérico para complementar.

**Comment by CleissonVieira** [comment]
@practice-uffs/con peço auxílio de como disponibilizar essas informações na página. O que deve conter no texto informando sobre os eventos que auxiliamos (no momento semanas acadêmicas) de forma que isso fique claro?

**Comment by alessandrapedrotti** [comment]
> @practice-uffs/con peço auxílio de como disponibilizar essas informações na página. O que deve conter no texto informando sobre os eventos que auxiliamos (no momento semanas acadêmicas) de forma que isso fique claro?

O texto deve conter:
- Descrição de pra quais eventos o auxílio é ofertado;
- Descrição do que podemos fazer para ajudar, por ex: o practice oferece apoio técnico a realização do evento;
A descrição do que fazemos deve ser bem esmiuçada, sugiro que seja elencado em forma de lista
- O que NÃO  fazemos, por ex: o practice não se responsabiliza pela gravação do evento;
- Termos e condições que a pessoa pode solicitar o serviço, por ex: deve ser solicitado com 3 dias de antecedência.

Isso foi o que me veio a mente. Acredito que os outros membros da @practice-uffs/con-material vão ter mais apontamentos.

Obs: os exemplos que eu coloquei acima são superficiais e meramente ilustrativos.

**Comment by CleissonVieira** [comment]
@Dovyski O que você acha dessa estrutura que a @alessandrapedrotti informou assim? Pode ser desta maneira elaborado o texto para essa página? Tem informações a mais que podemos adicionar?

**Comment by Dovyski** [comment]
O @phdmauricio é o chefe do serviço de auxílio de video conferencias, ele pode conferir as demandas. Em relação Em relação ao que a @alessandrapedrotti comentou, eu concordo 100%.
