### ISSUE TITLE
Criar página /servico/fluxo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#18]
Essa página deve conter informações sobre como o PRACTICE trabalha, ex.: sprints, horizontes, etc. Talvez algumas das imagens que foram apresentadas na primeira reunião de trabalho possa ser utilizada aqui, como distribuição de equipes, etc.

**Comment by CleissonVieira** [comment]
Para quem pegar essa tarefa: foi criado o arquivo fluxo.md em: _pages -> servico -> fluxo.md

**Comment by CleissonVieira** [comment]
@practice-uffs/con  @Dovyski Você ou algum outro coordenador poderiam me ajudar nessa tarefa? Eu não sei qual o nível do fluxo de trabalho a ser apresentado, exatamente como é desde o princípio desse fluxo. Estou um pouco perdido.
Criei [ESSE](https://docs.google.com/document/d/1z4Sm7hHlDLbnWi_mCN5w8gmo83X7ZUpkODbAiJNusYI/edit) doc para criar o conteúdo e depois [passar](https://practice.uffs.cc/servico/fluxo) para o site do PRACTICE.
