### ISSUE TITLE
Atualizar página de pessoas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#2]
Atualmente a [página de pessoas](https://practice.uffs.cc/pessoas) está mostrando as informações do curso de computação. Atualizar a página para conter os nomes dos membros e as equipes a seguir:

### Coordenação geral

Mauricio
Fernando

### Coordenação técnica-pedagógica

Caimi
Elis

-----

### Texto e roteiro

Isabeli Reik - @isabelirk
Alessandra Pedrotti - @alessandrapedrotti
Maria Gelain - @mariagelain
Lucas Ferreira - @lucasgalize

### Imagem, vídeo e som

Matheus Negrão - @MaNegrao
Vinícius do Reis - @vini2reis
Igor Matheus - @oigor

## Desenvolvimento de software

Andrew M. Silva - @andrewmsilva
Cleisson Vieira - @CleissonVieira
Estela Vilas Boas - @estelavilasboas

## Auxílio organizacional

Vinícis França - @franca20

**Comment by andrewmsilva** [comment]
Okay, vou fazer. Pode me colocar nos Assignees, se quiser.

**Comment by Dovyski** [comment]
Tu (e qualquer um) pode se auto-colocar no assignees quanto assumir uma tarefa, @andrewmsilva , dai fica mais ágil e fácil.
