### ISSUE TITLE
Criar pelo menos 5 notícias para o site

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#22]
Todas as notícias do site agora são cópias das notícias do curso de computação. Isso precisa ser alterado. Para cumprir essa issue, apague todas as notícias relacionadas com o site do curso, depois crie pelo menos 5 notícias do próprio PRACTICE.

Ideias de noticias:

* A UFFS já fez uma notícia sobre a ASSITEC e o PRACTICE, podemos copiar ela na íntegra e mencionar que "Essa notícia foi originalmente postada em XX de Junho de 2020 no site da UFFS".

* Informação sobre o vídeo promocional do programa

* Live que aconteceu em Laranjeiras do Sul para apresentação do programa lá

* Estamos trabalhando em um aplicativo

**Comment by phdmauricio** [comment]
esta aqui ja pode ir: https://www.anchieta.sc.gov.br/noticias/index/ver/codNoticia/625796/codMapaItem/8589

**Comment by andrewmsilva** [comment]
Sobre o app do PRACTICE, tem como alguém tirar um print de tela de como o app está agora e dizer quais seriam as funcionalidades previstas pra ele (@Dovyski)? Assim eu já escrevo a notícia bem bonitinho ;)

**Comment by phdmauricio** [comment]
Amanhã teremos uma notícia importante para o site;.
