### ISSUE TITLE
Inserir os servidorrs de Laranjeiras na equipe do site

### ISSUE THREAD

**Issue by phdmauricio** [practice-uffs/website-programa#23]
Inserir os servidores de Laranjeiras do Sul na equipe do PRACTICE no site....

**Comment by phdmauricio** [comment]
O PRACTICE conta com uma equipe de estudantes e professores que se dedicam de forma organizada e eficiente para realizar diversos tipos de atividades.

Substituir "professores" por  "servidores"

**Comment by phdmauricio** [comment]
@CleissonVieira olhe os comentários acima

**Comment by phdmauricio** [comment]
@CleissonVieira e inclua os dois servidores de Laranjeiras na descrição

**Comment by CleissonVieira** [comment]
> @CleissonVieira e inclua os dois servidores de Laranjeiras na descrição

Desculpa @phdmauricio não entendi, de que forma incluir dois servidores de Laranjeiras na descrição? A descrição está generalizada.

**Comment by lcaimi** [comment]
Estão faltando os nomes dos seguintes membros da equipe do Practice:

- Equipe Técnica Pedagógica Campus Laranjeiras do Sul:
 Alexandre Manoel dos Santos 
 Luciano da Silva Lopes

**Comment by CleissonVieira** [comment]
@lcaimi @phdmauricio 
Para concluir, é necessário colocar essa nova categoria: _Equipe Técnica Pedagógica Campus Laranjeiras do Sul_.
Ou insiro eles na _Coordenação técnica-pedagógica_ ?

**Comment by lcaimi** [comment]
Coloca uma nova categoria: Equipe Técnica Pedagógica Campus Laranjeiras do Sul.
