### ISSUE TITLE
Criar página /recursos

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#25]
Essa página deve seguir o layout da página "serviços". A diferença é que em vez de serviços listaremos os materiais (cartilhas). A @practice-uffs/con-material informará dia 27/07 sobre quais cartilhas/documentos ficarão disponíveis.

**Comment by andrewmsilva** [comment]
Se possível, alguém da @practice-uffs/con-material poderia comentar nesta issue quais materiais ficarão disponíveis no site? Seria conveniente se fossem adicionados os links para eu baixar os respectivos materiais, assim o processo todo seria agilizado.

**Comment by Dovyski** [comment]
Até que a con-material defina quais materiais ficarão disponíveis no site, vocês podem verificar todas as cartilhas que foram feitas (ver issues) e listar todas elas.
