### ISSUE TITLE
Adicionar no site do PRACTICE um formulário do Projeto Além da Fronteira.

### ISSUE THREAD

**Issue by phdmauricio** [practice-uffs/website-programa#26]
Criar um formulário que esteja disponível no menu do site do Practice com o nome "Projeto Além da Fronteira".
Este formulário deve receber as seguintes informações dos visitantes:

1. Nome:
2.Campus:
3. Área de Conhecimento: 
Tema da Capacitação: (Neste ponto eu vou sugerir 7 temas e teria que criar outra opção "Outros" com a possibilidade de informação de um texto curto pelo cliente.
4. Dia da semana com disponinbilidade:
5. Turno da disponibilidade: (Matutino; Vespertino ou Noturno).
@practice-uffs/dev-web

**Comment by phdmauricio** [comment]
Cancel está requisição. Não será mais necessária. Obrigado.

**Comment by phdmauricio** [comment]
Obrigado @CleissonVieira , mas não é mais necessária.

**Comment by CleissonVieira** [comment]
Certo @phdmauricio estou finalizando a issue então.

**Comment by phdmauricio** [comment]
ok

**Comment by phdmauricio** [comment]
Desculpe-me pelos transtornos.

**Comment by CleissonVieira** [comment]
Sem problemas hehe
