### ISSUE TITLE
Correções textuais do site

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/website-programa#27]
Conforme combinado na reunião de sexta (24/07), fiz a correção textual do site. A seguir, meus apontamentos.
Devo esclarecer que os comentários a seguir não tratam unica e exclusivamente do material textual do site, mas de um conjunto de questões que observei nessa leitura que podem ser melhorados.
Tentei separar os apontamentos em sessões, seguindo a segmentação do próprio site.

@practice-uffs/con-digital 

DESTAQUES

- [x] As atualizações das notícias estão aparecendo com um misto de português e inglês (como na imagem abaixo). Corrigir em todas as ocorrências e deixar tudo em português.

 
![image](https://user-images.githubusercontent.com/66969126/88575185-d7b5d800-d019-11ea-9b90-14aaa8024bbd.png)

- [x] Caso o texto das notícias tenha sido escrito por um membro do programa, é importante sinalizar isso, assim como já está sendo feita a marcação da notícia original em caso de réplica.

BARRA DE INFORMAÇÕES AO FINAL DA PÁGINA

- [x] Ao invés da palavra “social” indicando os perfis nas redes sociais e github, seria melhor colocar de fato “redes sociais” ou “redes sociais do PRACTICE”.

- [x] O link do twitter da em uma conta que não existe, acredito que como mudaram as contas, ainda não foi feita essa alteração no site.

O QUE É PRACTICE

Copiei e corrigi os trechos do texto que julguei necessário fazer alterações.

- [x] No resumo: “Na UFFS, os diferentes cursos de graduação e pós-graduação, assim como pró-reitorias, construíram instrumentos que mapearam as habilidades dos professores em manusear diferentes tecnologias para a construção de aulas semipresenciais, bem como as condições de acesso dos estudantes”.

![image](https://user-images.githubusercontent.com/66969126/88575272-02a02c00-d01a-11ea-99c9-65c5f3b403c0.png)

- [x] A listagem dos 7 eixos de atuação do programa pode ser apresentada em lista de fato, não em um bloco de texto como está agora (imagem acima). Desta forma ficará mais fácil de ler e também será visualmente mais agradável.

- [x] Logo abaixo do trecho comentado acima temos a frase “vídeo de apresentação do programa embutido na página, link: https://www.youtube.com/watch?v=MBX_Ij4qSPc”. Podemos mudar para: “Vídeo de apresentação do programa” ou “Aqui está o link para você assistir o vídeo de apresentação do programa”.

- [x] Elaborei o trecho a seguir pensando que ele possa substituir o que está como objetivo do programa. Mantive a mesma ideia, só reestruturei algumas partes, já que o atual está com alguns erros de escrita que dificultam o entendimento:
 “Baseado em metodologias ativas de ensino, o PRACTICE tem por objetivo estruturar ambientes, capacitar agentes educacionais, produzir e mediar a produção de conteúdos educacionais que promovam a inovação do processo de aprendizagem de estudantes em componentes curriculares e extracurriculares da UFFS”. 

- [x] Na listagem de objetivos específicos, o quinto item “Criar e desenvolver conteúdos digitais, bem como auxiliar na produção deste material por demanda direta dos docentes e taes”, se “taes” é uma sigla, deixar em letras maiúsculas e indicar ao lado entre parênteses o nome completo a que ela diz respeito.

EQUIPE

- [x] No texto de apresentação: “O PRACTICE conta com uma equipe de estudantes, professores e servidores que se dedicam de forma organizada e eficiente para realizar as atividades que o programa propõe.”

- [x] Nas descrições da coordenação geral, pedagógica e equipe técnica de Laranjeiras - Deixar padronizado em todas as ocorrências frases como “Doutor em xx” ou “Doutorado em xx”. Escolham apenas uma das duas formas.

- [x] A listagem de títulos também deve estar clara, se são uma única frase, favor colocar vírgulas, se estiverem em frases diferentes, arrumar para que fiquem em lista. Reparei que na descrição do prof Maurício e na da Elisângela tem esse erro.

Na parte da produção de conteúdo:
- [x] A equipe é de texto e imagem, não de texto e roteiro, como consta no site.
- [x] Na minha apresentação (Alessandra), o nome correto do curso que deve aparecer ali é Letras – Português e Espanhol.
- [x] Onde consta “imagem, vídeo e som” deixar apenas “vídeo e som”, pois trata-se da equipe con-mídia.

FLUXO DE TRABALHO

Primeiramente, achei que, no geral, o texto dessa página ficou muito técnico e não sei se é fundamental que apresentemos essas informações dessa maneira para o público. Dito isso, eu sugiro que a parte da divisão das equipes seja ou apagada ou reformulada, para algo como: “Para atingir os objetivos de cada horizonte, trabalhamos com equipes que atuam em frentes distintas, como a produção de conteúdo e desenvolvimento de software”. Enfim, isso é só uma ideia, caso não seja viável a mudança, segue a correção do que está atualmente no site:

- [x] Nos objetivos do horizonte dois, mudar “Material para consumo da comunidade externa” para “materiais para uso da comunidade externa”. Aqui também vale descrever quais materiais são esses.
- [x] Acho que vale adicionar uma pequena descrição do que é cada horizonte, pode ser entre parênteses no mesmo tópico que ele já é apresentado, por exemplo: Horizonte zero (objetivos de curto prazo).

- [x] Podemos tirar o subtítulo “horizontes, equipes e sprints” abaixo de “fluxo de trabalho".

- [x] Nos objetivos do horizonte zero, mudar “produção de vídeo” para “produção de vídeos”.
- [x] Mudar de “Atualmente trabalhamos em cima de 3 horizontes” para “Trabalhamos com nossas metas divididas em 3 horizontes” ou algo similar. 

No trecho "fluxo de trabalho das equipes":

- [x] Mudar o texto atual para: 
"A sprint é iniciada com uma reunião de planejamento, que define as tarefas que serão desenvolvidas. Essas tarefas então são inseridas em um Quadro de Tarefas Scrum pelo qual os membros de cada equipe tem acesso para realiza-las.
Após 7 dias, é realizada uma reunião de andamento, pela qual se verifica detalhadamente o andamento do trabalho das equipes visando aperfeiçoar o fluxo de trabalho.
O fechamento da sprint acontece ao final do período de 14 dias e cabe a gerência encerrar as tarefas que foram desenvolvidas no período ou mantê-las abertas para a próxima sprint, caso o resultado não tenha sido satisfatório”.

PARCERIAS

- [x] Mudar a descrição do FronteiraCast de “O FronteiraCast é um novo projeto de cultura fundado em 2019 por estudantes de Ciência da Computação da UFFS Campus Chapecó em conjunto com o coordenador do curso Fernando Bevilacqua e professor Maurício Bozatski da área da Filosofia” para “O FronteiraCast é um projeto de cultura fundado em 2019 por estudantes da UFFS Campus Chapecó em conjunto com o coordenador do curso de Ciência da Computação Fernando Bevilacqua e professor do curso de Filosofia Maurício Bozatski”.

As guias do site que não aparecem nessa listagem ou não estão completos, ou não possuem erros.

**Comment by CleissonVieira** [comment]
@Dovyski @practice-uffs/con   Conforme imagem abaixo, poderia:
1. Nos oferecer uma breve explicação sobre os 3 horizontes para que possamos colocar na página de Fluxo de trabalho.
2. Quais materiais (conforme horizonte dois) vamos fornecer para uso da comunidade externa?
3. Opinião sobre a parte da divisão das equipes conforme Alessandra informou, apagamos ou reformulamos? 

![image](https://user-images.githubusercontent.com/29258164/88612028-a8768980-d060-11ea-9c5e-07c1a3dec6c4.png)

**Comment by Dovyski** [comment]
No momento, vamos manter a divisão das equipes listadas no site. No futuro, podemos refinar o conteúdo conforme o que a @alessandrapedrotti comentou.

**Comment by alessandrapedrotti** [comment]
Conversando com o Cleisson lembrei de mais um detalhes do site que pode ser melhorado: trocar as fotos atuais que não estão muito boas para as que os colegas disponibilizarão na issue #62 do repositório programa.
