### ISSUE TITLE
Notícia sobre lançamento oficial

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/website-programa#28]
Criar uma notícia sobre o lançamento oficial do PRACTICE, incluindo links para a Live de lançamento e para as redes sociais. Adicionar essa notícia nos Destaques.

**Comment by Dovyski** [comment]
Relacionada a  https://github.com/practice-uffs/programa/issues/71. Fechar ambas issues quando tudo estiver pronto.
