### ISSUE TITLE
Atualizar página /servico/media

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#31]
Remover a ilustração atual da página e trocar o texto: 

> **Áudio e vídeo**
> Equipe responsável pela criação de conteúdo de Áudio e vídeo.

por

> **Áudio**
> Para abranger o maior número de formatos que podem ser utilizados, separamos uma breve explicação dos produtos de áudio que podemos oferecer. A nossa equipe de media disponibiliza nossos formatos tanto para edição como para produção em nosso estúdio, atendendo um dos seguintes modelos

Em seguida, colocar o conteúdo [desse documento](https://docs.google.com/document/d/1uuU5YbcKqEp1kDLo3LjIEQVl5QHnhQTcup0sMVOFyNU/edit#) na página. Esse texto está ainda em produção em https://github.com/practice-uffs/programa/issues/44, mas já pdoe ser usado agora.

**Comment by lcaimi** [comment]
@CleissonVieira  ver comentário na issue #32
