### ISSUE TITLE
Adicionar serviços de vídeo na página /servico/media 

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#32]
Depende de: https://github.com/practice-uffs/website-programa/issues/31

Depois que #31 for feita, criar uma nova seção, com um ícone apropriado e o seguinte texto ao lado:

> **Vídeo**
> Esses são os formatos de vídeo tanto para edição como para produção em nosso estúdio

Em seguida, colocar o conteúdo [desse documento](https://docs.google.com/document/d/1brS3rAwuheaVX3_I9F-aHvbShriDRXIeMBDkLe5pOYc/edit#) na página. Esse texto está ainda em produção em https://github.com/practice-uffs/programa/issues/42, mas já pode ser usado agora no site.

**Comment by lcaimi** [comment]
O formato de áudio foi revisado e está atualizado [neste documento](https://docs.google.com/document/d/1brS3rAwuheaVX3_I9F-aHvbShriDRXIeMBDkLe5pOYc/edit#).

O formato de vídeo, disponível [neste documento](https://docs.google.com/document/d/1brS3rAwuheaVX3_I9F-aHvbShriDRXIeMBDkLe5pOYc/edit), deve ser incorporado nos mesmos moldes logo na sequência.

@CleissonVieira
