### ISSUE TITLE
Criar a página "/servico/estudio"

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#45]
A gravação feita no estúdio é parte do serviço de audio e vídeo, mas será difícil dos clientes entenderem isso. Para garantir um fluxo fácil para a equipe e uma organização maior, vamos criar a página "/servico/estudio", listada como "Estúdio" no menu "Serviços".

* A página pode seguir o layout padrão com as seguintes informações:

* [x] Título: Gravação em estúdio
* [x] Subtítulo: Você precisa produzir vídeos com uma estrutura peculiar ou com recursos muito específicos? O serviço de estúdo do programa pode te ajudar.
* [x] Seção na página chamada "infra-estrutura", contendo duas fodos, lado a lado, de um estúdio. No momento não temos essas fotos, então qualquer placeholder pode ser usado.
* [x] Seção "Agendamento", contendo o texto "A utilização do estúdio está condicionada à disponibilidade de horário mediante agendamento. Confira abaixo os agendamentos existentes para cada um dos nossos nossos estúdios".
* [x] Aina na seção "Agendamento", colocar depois do texto a visualização de várias agendas do Google Calendar integradas na própria página (@lcaimi deve fornecer os links para as agendas aqui nessa issue).

**Comment by lcaimi** [comment]
Links para as agendas:

Agenda do estúdio campus Chapecó
https://calendar.google.com/calendar?cid=NnNsdGg0bWZuMDMzZzJtZHQyMHRsN2Vpa2tAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Agenda do estúdio campus Laranjeiras do Sul
https://calendar.google.com/calendar?cid=Z3RvY21zZHJtM3V0ZzU5b2c5MGhkYWo1cGtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Agenda das Lives 
https://calendar.google.com/calendar?cid=dm9lNGVta241NjRzdHE0NWlsdmxkYTBtdjBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
