### ISSUE TITLE
Refinar a página inicial do programa

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#46]
A página inicial atualmente contém notícias em destaque e uma lista de notícias. A página será alterada agora para conter outras informações, seguidas desses destaque e notícias ("empurrar as infos de notícias para baixo e colocar um conteúdo novo no lugar delas").

O conteúdo novo que será colocado tem o seguinte layout:

![image](https://user-images.githubusercontent.com/512405/90761378-b2835500-e2b9-11ea-8baf-46b044762970.png)

Você pode obter o código fonte desse exato layout [nesse projeto](https://github.com/grintex/qualidade-agua). No caso do PRACTICE, as seguintes informações serão usadas no layout:

* Remover o título "Informações" (o usuário verá direto os 3 blocos de informação)

Para os textos a serem colocados nos blocos 1, 2 e 3, e nas demais seções desse layout novo, a @practice-uffs/con-conteudo ajudará na elaboração. Mediar e tratar com eles para que isso seja feito.

**Comment by CleissonVieira** [comment]
Novo layout incluido. @practice-uffs/con-conteudo como ficará o conteúdo dessa parte? O que podemos formular? 

![image](https://user-images.githubusercontent.com/29258164/91086619-8c491680-e625-11ea-8a67-a8a5d288e0f2.png)
![image](https://user-images.githubusercontent.com/29258164/91086657-98cd6f00-e625-11ea-9504-ca80a8f32bc4.png)

**Comment by Dovyski** [comment]
Utilizar as seguintes informações de texto:

Para os 3 primeiros blocos:

# Tecnologia
Buscamos criar soluções tecnológicas para aprimorar o ambiente acadêmico de ensino e aprendizagem.

# Comunidade
Não estamos sós, focamos na habilidade pedagógica e tecnológica tanto de servidores quanto estudantes.

# Independência
Nossa missão é empoderar tecnologicamente pessoas para que a tecnologia seja ajuda, não barreira.

------

Para o bloco de texto principal.

Trocar "O que é esse serviço?" e o texto existente pelos seguintes blocos:

# O que é o PRACTICE?

O Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional (PRACTICE) objetiva estruturar ambientes e capacitar agentes educacionais para a produção e mediação de conteúdos por meio de tecnologias.  Visamos contribuir para a promoção da inovação no processo de ensino-aprendizagem da UFFS, seja em componentes curriculares e extracurriculares, projetos ou iniciativas.

## O que fazemos?

Capacitação didática de docentes para a oferta de aulas via telepresença, de maneira síncrona e assíncrona, bem como o fomento para o desenvolvimento de tecnologias inovadoras próprias da UFFS voltadas à interação, criação, curadoria e distribuição de conteúdos de acesso público.

Também trabalhamos pelos estudantes para que tenham voz de sugestão de adequação de programas de Assistência Estudantil para oportunizar a participação de todos, sem prejuízo, nas atividades de envolvam tecnologia.

## Como fazemos e trabalhamos?

Trabalhamos pela estruturação de ambientes que possibilitem a gravação, transmissão, edição e produção de conteúdos educacionais nas mais variadas plataformas de distribuição de conteúdo. Nossas soluções incluem, por exemplo, adaptação de algumas salas de aulas atuais da UFFS para o oferecimento de aula em tempo real por telepresença.

Todo nosso trabalho é feito de forma pública e transparente através do [Github](https://github.com/practice-uffs). Nossas soluções tecnológicas são open-souce, livres para todos usarem. Nossos materiais são gratuítos e reutilizáveis ou adaptáveis. Acreditamos que a inovação aberta, com ciência e tecnologia a favor da comunidade, fará a diferença no avanço da educação.


------

Para a parte do aplicativo:

# Aplicativo móvel
Todas nossas soluções são acessíveis através de nosso aplicativo para smartphones.

Queremos que a tecnologia chege até servidores e estudantes de forma fácil, sem complicações. Queremos ferramentas na palma da mão de cada um dos membros de nossa comunidade acadêmica. Trabalhamos para que nossos avanços estejam disponíveis, em primeira mão, em seu celular, para um uso fácil e imediato.

**Comment by Dovyski** [comment]
Ficou fantástico, e os ícones são um luxo 😄🥳
