### ISSUE TITLE
Adicionar um banner bonito do PRACTICE e ajustar com a navbar

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/website-programa#5]
Atualmente (07/07/2020), a página inicial ainda está com a mesma imagem "hero" que está no site de [https://cc.uffs.edu.br/](https://cc.uffs.edu.br/) (logo abaixo da navbar). Eu sugiro que seja feito um banner bem bonito com as cores do PRACTICE e com algum texto sobre o projeto. Então, a navbar podia adotar um comportamento transparente quando a rolagem estiver no topo, evidenciando o banner bonito (de preferência direto com bootstrap).

**Comment by estelavilasboas** [comment]
Banner disponível na [pasta da Issue](https://drive.google.com/drive/u/0/folders/1lL2p2teIfXXRRPF-94xS6PTSIGZC78zt) para os interessados.
