### ISSUE TITLE
Padronizar tamanho de notícias em destaque mostradas na página inicial

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#50]
Atualmente as notícias em destaque são mostradas em tamanhos e alinhamentos diferentes, que são afetados pela quantidade de texto de cada notícia:

![image](https://user-images.githubusercontent.com/512405/92279229-3a2dae00-eecd-11ea-88ba-2b3ce3edad69.png)

As notícias precisam ser alinhadadas em tamanho e posicionamento. Por exemplo, o site do curso de Computação tem isso:

![image](https://user-images.githubusercontent.com/512405/92279277-4f0a4180-eecd-11ea-9fbe-f6e2534f749e.png)

Embora o site de CC esteja em dark mode, você pode utilizar o CSS e HTML usado nele para deixar o alinhamento das notícias do site do PRACTICE com a mesma estética.

**Comment by lcaimi** [comment]
Também é necessário organizar por ordem de data. Tanto na parte de destaques, quanto na parte de notícias.

Na parte de notícias estão algumas muito antigas, sem aparecer as mais recentes.

**Comment by CleissonVieira** [comment]
> Também é necessário organizar por ordem de data. Tanto na parte de destaques, quanto na parte de notícias.
> 
> Na parte de notícias estão algumas muito antigas, sem aparecer as mais recentes.

Verifiquei agora essa mensagem. @lcaimi os destaques a principio não está por ordem de data pelo fato de nós ter a opção de escolher o que queremos que fique nos destaques. As noticias listadas abaixo dos destaques (conforme print abaixo) está por ordem de data, porém ali não são listadas o que está nos destaques, se verificar temos 8 noticiais, as dos destaques e as listadas abaixo dos destaques (por isso essa lista está antiga, porque não listamos nos dois locais ao mesmo tempo, se não destaque e noticias seriam o mesmo).

![image](https://user-images.githubusercontent.com/29258164/92644095-2ca36a00-f2b9-11ea-99dd-fad8386f5e1e.png)

Deu para entender Caimi? talvez quer que seja listado o que existe nos destaques nas "Últimas notícias" também? (porém se colocar nas últimas noticias e ordenar por data os destaques, sendo as últimas notícias, perde o sentido de existir "Destaques).

**Comment by lcaimi** [comment]
Entendi, mas acho que faz mais sentido os destaques ficarem ordenados por data.
