### ISSUE TITLE
Criar página de portfolio

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#51]
Atualmente a página está vazia. Criar ela com a seguinte estrutura:

- Texto e ícone no começo da página, como existe em todas as outras páginas. Utilizar o seguinte texto para o portfólio:
> Conheça os resultados dos mais diversos trabalhos executados pela equipe do programa desde sua criação.

## Eventos virtuais

O programa já auxiliou na execução de diversos eventos virtuais, como lives de capacitação de setores da universidade e semanas acadêmicas. Nossa equipe utiliza as melhores tecnologias e recursos para enriquecer as transmissões.

> Colocar aqui a foto que o @MaNegrao colocou nos stories do practice do PC dele durante uma live do NAP

Abaixo estão algumas das transmissões que realizamos recentemente:

> Colocar aqui, lado a lado, 4 flyers das lives realizadas pelo practice. Tentar escolher aqueleas que tiveram maior audiência e/ou que mostre clientes difentes. Abaixo está um exemplo da página de recursos de como eu quero que os flyers sejam mostrados (você pode obter esses flyers na issue https://github.com/practice-uffs/programa/issues/95):

![image](https://user-images.githubusercontent.com/512405/92279809-7a416080-eece-11ea-9621-8f4fcba5e739.png)

## Gravações em estúdio e vídeos

Além de editar e pós-produzir vídeos e materiais enviados ao programa pelos docentes da UFFS, também atendemos demandas de gravação realizadas em nosso estúdio (atualmente disponível no campus Chapecó, em breve nos demais campi).

> Colocar aqui duas fotos, lado a lado: uma das fotos é a que eu fiz da @alessandrapedrotti e da @mariagelain no estúdio, a outra é do @MaNegrao mexendo na mesa de som. Confirmar com eles se eles autorizam a publicação dessas fotos. Se não autorizarem, achar alguma foto no acervo do programa que sirva para isso.

**Comment by CleissonVieira** [comment]
@Dovyski  Informativo: essa tela já foi criada com base [nessa issue](https://github.com/practice-uffs/website-programa/issues/43). Porém estava com bug e inacessível. Acabei de arrumar esse bug:
![image](https://user-images.githubusercontent.com/29258164/92523182-52b40600-f1f6-11ea-8141-2cd6617d1332.png)

Vou reformular de acordo com essa issue. (#51)

**Comment by lcaimi** [comment]
Os flyers das Lives já realizadas estão na pasta de saída da Issue /programa/#95
Sugiro que ao clicar no flyer ele direcione para respectiva Live.

**Comment by Dovyski** [comment]
Ok, pode reformular seguindo as instruções dessa issue (#55) e o que o @lcaimi comentou acima.

**Comment by CleissonVieira** [comment]
Concluído, só não estou encontrando a imagem da Ale e Maria @Dovyski , sabe me informar onde ela se encontra?

**Comment by Dovyski** [comment]
As fotos estão [nessa pasta aqui](https://drive.google.com/drive/folders/1CuwL700oelxpvQZmnBahDCQGyydm4lie). Para referência futura, materiais dessa natureza (fotos, vídeos, etc) que foram feitos para registro do nosso trabalho, estarão na pasta `Materiais -> Biblioteca de conteúdo -> Acerto de atividades do programa`.

**Comment by CleissonVieira** [comment]
No caso existem vídeos nessa pasta, é para tirar um print e colocar no site (obs: vai ficar meio ruim a qualidade) ou talvez você tem uma imagem que não foi feito upload para o drive?

**Comment by Dovyski** [comment]
Hum, se não tiver foto delas, então tem apenas vídeo. Talvez tu possa criar usar o próprio vídeo, já que ele é curtinho. Se colocasse ele sem um player ao redor e com autoplay, acho que ficaria legal. Isso se o vídeo for menor que 2Mb, se não precisamos da foto.

**Comment by CleissonVieira** [comment]
O de 3 segundos da 8.4mb

**Comment by Dovyski** [comment]
Nah, muito grande. Vamos com imagem então. Tenta achar um frame que funcione. Talvez até usar algo que exporte o vídeo em várias imagens para ter algo de mais qualidade.

**Comment by CleissonVieira** [comment]
Perfeito, vou fazer isso então, obrigado Fernando! =D
