### ISSUE TITLE
Melhorar feed RSS/atom

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#53]
O [feed.xml](https://practice.uffs.cc/feed.xml) do site contém informações úteis, porém precisamos de mais dados para podermos colocar isso no app do programa. O site do curso de CC tem um [feed.xml](https://github.com/ccuffs/cc.uffs.edu.br/blob/master/feed.xml) mais completo que podemos usar. Ao que eu imagino, deve dar para copiar e colar o `feed.xml` de CC no site do PRACTICE tudo funcionará sem alterações. Precisamos disso.

**Comment by andrewmsilva** [comment]
O XML gerado está retornando as notícias corretamente, mas as duas últimas são notícias exemplos e não deveriam estar sendo carregadas. Além de não seguirem o esquema padrão das outras notícias, essas duas estão em inglês. 

Vejam o exemplo abaixo:
![image](https://user-images.githubusercontent.com/18292676/92931769-54f6aa00-f41a-11ea-8b02-6b0e102ac9ee.png)

Thundercats Ho! 😂 

Requisito que essas duas últimas notícias sejam removidas.

**Comment by CleissonVieira** [comment]
Correção feita, arquivos desnecessários deletados.
