### ISSUE TITLE
Criar página `/portifolio/lives`

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#54]
Relacionado a: https://github.com/practice-uffs/programa/issues/95#issuecomment-690619863

Criar a página `/portifolio/lives` que lista todas as lives realizadas pelo programa. A página pode mostrar 4 flyers por linha, não 3 por linha como está na figura abaixo:

![image](https://user-images.githubusercontent.com/512405/92921449-7059b900-f40a-11ea-9ab5-c4760f644d75.png)

Na página `/portfolio`, na seção das lives realizadas, nós já mostramos algumas em destaque. Colocar um link lá com um texto "Ver todas lives realizadas` que leva para `/portfolio/lives`.

**Comment by CleissonVieira** [comment]
@Dovyski posso criar uma pasta no servidor `cdn.uffs.cc` para colocar esses flyers já que vão se acumular muitos ao decorrer do tempo? Ou indica armazenar no git mesmo?

**Comment by Dovyski** [comment]
Pode criar uma pasta no `cdn.uffs.cc` para isso, sim.
