### ISSUE TITLE
Atualização da página de Equipe

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/website-programa#55]
Com a inclusão de novos membros e exclusão de outros, é necessário atualizar a equipe do PRACTICE no site. Vale salientar que muitas equipes de trabalho e cargos também mudaram, então é importante verificar esses detalhes e mantê-los consistentes no site. Além disso, os voluntários devem ser adicionados à página de equipe. Deve-se utilizar as imagens colocadas na issue [167](https://github.com/practice-uffs/programa/issues/167).

Assim que a @practice-uffs/ger-auxilio atualizar esses dados em um documento, ele será disponibilizado aqui para ser usado como base para atualizar essas informações.

**Comment by alessandrapedrotti** [comment]
As informações estão sendo atualizadas [neste documento.](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=1145326100).

**Comment by CleissonVieira** [comment]
Pessoal, está confuso esse documento na coluna dos cargos. Favor responsável padronizar o nome do cargo de todos os participantes.
@alessandrapedrotti Não sei se é você quem tem permissão para editar hehe

![image](https://user-images.githubusercontent.com/29258164/95255750-407ab700-07f8-11eb-8a5a-90db86f3d5d8.png)

**Comment by CleissonVieira** [comment]
Dois membros faltantes nas descrições das Issues [167](https://github.com/practice-uffs/programa/issues/167)

Sendo que esse primeiro não tem área de atuação e o github dele não está na organização PRACTICE.

![image](https://user-images.githubusercontent.com/29258164/95258686-833e8e00-07fc-11eb-984c-85f88110506a.png)
![image](https://user-images.githubusercontent.com/29258164/95258744-92bdd700-07fc-11eb-893f-8fd6dc44c273.png)

Demais membros adicionados e alterados de acordo com a planilha que @alessandrapedrotti passou. Verificar se planilha está atualizada para todos os membros.

**Comment by alessandrapedrotti** [comment]
> Pessoal, está confuso esse documento na coluna dos cargos. Favor responsável padronizar o nome do cargo de todos os participantes.
> @alessandrapedrotti Não sei se é você quem tem permissão para editar hehe
> 
> ![image](https://user-images.githubusercontent.com/29258164/95255750-407ab700-07f8-11eb-8a5a-90db86f3d5d8.png)

Farei a padronização.

**Comment by alessandrapedrotti** [comment]
É necessário remover o Lucas Ferreira da página da equipe.

**Comment by CleissonVieira** [comment]
@alessandrapedrotti adicionar os voluntários? 
Se sim acredito que da para pedir para eles preencherem a [issue 167](https://github.com/practice-uffs/programa/issues/167)

![image](https://user-images.githubusercontent.com/29258164/95346913-b59aca80-0892-11eb-965f-57287f780c20.png)

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti adicionar os voluntários?
> Se sim acredito que da para pedir para eles preencherem a [issue 167](https://github.com/practice-uffs/programa/issues/167)
> 
> ![image](https://user-images.githubusercontent.com/29258164/95346913-b59aca80-0892-11eb-965f-57287f780c20.png)

Sim, eles devem ser adicionados ao site. Inclusive já os marquei na issue #167 para que eles façam suas apresentações.

**Comment by CleissonVieira** [comment]
@alessandrapedrotti  só para te atualizar, estou aguardando informações do @JeanCHilger que informou que logo vai postar na [issue 167](https://github.com/practice-uffs/programa/issues/167) suas informações e o [Rafael da Costa Guilman](https://github.com/rafaguilman) que não está atrelado a equipe PRACTICE no github consequentemente ainda não escreveu na issue descrita acima seus dados. 

Assim que eu tiver as informações dos dois atualizo o site e finalizo a Issue.
