### ISSUE TITLE
Criar página de histórico de membros

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/website-programa#56]
Visto que é inevitável haver rotatividade entre os bolsistas, voluntários e coordenadores do PRACTICE, é necessário criar uma página para mostrar uma tabela com o histórico de todos os membros. A tabela deve possuir o nome, vínculo (bolsista, coordenador ou voluntário), equipe de trabalho e tempo de atuação (ex: Março de 2020 a Dezembro de 2020, ou Março de 2020 até hoje).

Esta página pode ser acessível através de um link na página Equipe e é importante lembrar de caprichar no UI e UX, pois tabelas tendem a poluir e complicar a visualização.

**Comment by CleissonVieira** [comment]
[Clique aqui (Histórico de Membros PRACTICE)](https://practice.uffs.cc/equipe/historic/) para acessar a página criada nessa issue,
