### ISSUE TITLE
Ajustar ícone da página sobre

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#58]
Atualmente o ícone mostrado na [página sobre](https://practice.uffs.cc/sobre/) é algo destoante do resto do layout. Utilizar alguma animação lottie mais adequada no lugar desse ícone.

**Comment by Dovyski** [comment]
Isso foi comitado em algum lugar? O site continua igual.

**Comment by CleissonVieira** [comment]
A sim, o commit foi realizado no mesmo dia após você comentar hehehe Mas já está em produção desde o dia informado como concluída!
