### ISSUE TITLE
Ajustar layout da página recursos (cartilhas)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#60]
Atualmente os materiais estão listados um ao lado do outro. Criar uma seção "Cartilhas" e como conteúdo dela mostrar os materiais da seguinte forma (alternando a ailustração na direita, depois ilustração na esquerda, etc):

![image](https://user-images.githubusercontent.com/512405/96266680-4bbea700-0f9d-11eb-98c9-827501b2e6f4.png)
![image](https://user-images.githubusercontent.com/512405/96266695-51b48800-0f9d-11eb-8c23-9795dc6f25ae.png)

Colocar o título da obra no título do bloco (por exemplo, "Dicas de produção de videoaula"), e um pequeno resumo (talvez o parágrafo inicial do conteúdo da própria obra).

Embora a segunda imagem de referência acima, com o gráfico na direita, não tenha o botão de download junto ao texto na esquerda (estão os logos da Adobe, etc), isso é meramente ilustrativo. Queremos um botão de download em todos os blocos (como ilustrado na primeira imagem de referência).

**Comment by CleissonVieira** [comment]
Issue concluída, porém não foi possível realizar o download do arquivo através do servidor. 

Exemplo:  (dessa forma realiza o download normalmente, é uma imagem que temos nas pastas do código)
![image](https://user-images.githubusercontent.com/29258164/96778296-da7a5c00-13c1-11eb-8777-e833029b0e63.png)

Agora se eu utilizo o file que é o pdf que está no servidor, ele abre em outra guia que existe um botão para realizar download, conforme segunda imagem das duas abaixo: 
![image](https://user-images.githubusercontent.com/29258164/96778374-ff6ecf00-13c1-11eb-9e12-d15ef7d36250.png)

![image](https://user-images.githubusercontent.com/29258164/96778444-1a414380-13c2-11eb-84c0-b5273e638544.png)


Image realiza download normalmente, file não realiza download: (usado image para testar)
![image](https://user-images.githubusercontent.com/29258164/96778539-393fd580-13c2-11eb-8076-4b8bf9110fc5.png)
