### ISSUE TITLE
Criação de página para prazos

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/website-programa#64]
Conforme o discutido nas últimas reuniões de líderes, decidimos que é importante ter no site uma página que reúna as informações sobre os prazos de solicitação e produção dos produtos e serviços do practice.

A partir do que foi elaborado [nesta issue](https://github.com/practice-uffs/programa/issues/184), favor  criar um tópico na página de fluxo de trabalho com o título "Entenda os prazos de solicitação" ou "Quando meu pedido será atendido?" ou, ainda, criar uma nova página para essas informações.

É importante que o texto produzido e a tabela nº2 estejam nessa página.

**Comment by CleissonVieira** [comment]
Concluída, [acesse aqui](https://practice.uffs.cc/servico/prazos-de-solicitacao/) para ver como ficou.

**Comment by alessandrapedrotti** [comment]
> Concluída, [acesse aqui](https://practice.uffs.cc/servico/prazos-de-solicitacao/) para ver como ficou.

A página ficou linda! Sugiro apenas colocar o recuo de parágrafo e justificar o texto.
