### ISSUE TITLE
Correções no texto do Web Feedback

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/website-programa#65]
O texto de apresentação do Web Feedback apresenta vários erros ortográficos. Tanto na versão de produção quanto na versão de desenvolvimento.

Vou fazer os apontamentos nas imagens e também num texto abaixo das mesmas.

Apontamentos nas imagens (grifados em vermelho)
![image](https://user-images.githubusercontent.com/12415747/97440326-16537b00-1906-11eb-8a6a-e0f60858c113.png)
- serviçoes -> serviços
- weeb -> web
- voccê -> você
- weeb -> web
- platafroma -> plataforma
- nosso -> nossos
- "inovação da UFFS, crescimento..." -> "inovação da UFFS. Crescimento ..."

![image](https://user-images.githubusercontent.com/12415747/97441186-3172ba80-1907-11eb-81e0-c4099b5214b0.png)
- experiencia -> experiência
- sujestões -> sugestões
- opniões -> opiniões

Acho também que deve mudar de "Bem vinde" para "Bem vindo" pois não faz sentido apenas esta página do projeto estar adaptada para a linguagem livre de gênero enquanto todas as demais continuam. O próprio texto interno não está adaptado.

**Comment by oraphaBorges** [comment]
Corrigido os erros apontados.

**Comment by lcaimi** [comment]
Reabri pois a maioria dos erros ainda estão presentes:
[https://qa.mural.practice.uffs.cc](https://qa.mural.practice.uffs.cc)
[https://mural.practice.uffs.cc](https://mural.practice.uffs.cc)
