### ISSUE TITLE
Alterar equipes de alguns membros

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/website-programa#66]
Tem alguns membros que estão na equipe errada, por conta da indefinição que tínhamos antes, mas agora estamos com as equipes totalmente definidas, então isso pode ser corrigido.

A relação de membros pode ser verificada no [link](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0)

> Minha sugestão é de que podemos fazer da seguinte maneira separando o mídia do "Conteúdo" no site:

## Produção de Conteudo ##
- Equipe con-con

### Transmissões ao vivo ##
- Luiza
- Matheus
- Milena
- Pedro
- Rafael

### Áudio, Vídeo e Animações ###

- Amanda
- Luiz
- Robison
- Vinicius Reis

> Outro ponto é a equipe de comunicação e ger-aux, que em minha sugestão também pode ser separada:

## Auxilio Gerencial ##
- Claudineia
- Vinicius França

## Comunicação ##
- Ana
- Morgana

(eu coloquei só os primeiros nomes pra referenciar)

CC : @practice-uffs/dev-web

**Comment by CleissonVieira** [comment]
Mantive apenas um grupo o "Produção de conteúdo", pois  o que há em "Produção multimídia" já é uma produção de conteúdo. Dividi apenas em subtítulos.
![image](https://user-images.githubusercontent.com/29258164/99159073-100c1f80-26b8-11eb-8757-469a564434c2.png)

Sobre a divisão do "Auxílio Gerencial" e "Comunicação" estou verificando com os membros uma melhor forma de informar essas equipes e seus integrantes.
