### ISSUE TITLE
Alterar página de "evento virtual" para "Transmissões ao Vivo"

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/website-programa#67]
A página de "evento virtual" está vazia. Podemos reestrutura-la agora que estabelecemos bem esse serviço. 

A primeira coisa é renomear a página para "Transmissões ao Vivo"

Creio que no texto da página podemos colocar o texto do panfleto de divulgação, que já está revisado e pronto:

> O PRACTICE oferece auxílio na produção e realização de eventos, com organização e transmissão online. As solicitações de eventos online devem ser realizadas com, no mínimo, 8 dias úteis de antecedência da data do evento, para fins de organização.
> O programa possui uma equipe especializada para oferecer auxílio técnico organizacional na produção e execução de transmissões ao vivo para os mais diversos órgãos da UFFS, as quais podem ser realizadas nas redes sociais do PRACTICE, ou onde o solicitante desejar. Os eventos podem ter diversas finalidades:
> 
> - Produção e realização de semanas acadêmicas virtuais;
> - Produção e organização de eventos institucionais virtuais, por exemplo, o “Café com Pesquisa”;
> - Transmissões para diretoria de campus e afins;
> - Transmissões para coordenações acadêmicas e de cursos.

Além disso, mover a agenda do google de lives da pagina "estudio" para essa pagina "Transmissões Ao Vivo"

![image](https://user-images.githubusercontent.com/31110971/99125134-3cee0300-25e2-11eb-97c8-1b41b35777b2.png)

Também sugiro utilizarmos a ilustração da [pasta](https://drive.google.com/drive/folders/1irrVSenorZMwOBKOiIZKYWHSwKOU0ZHN), selecionada do Undraw.io

E no final da pagina podemos colocar um link para o portfólio, onde tem as lives realizadas e o e-mail para solicitar o serviço

> Você pode conferir algumas das transmissões auxiliadas pelo PRACTICE em nosso portifólio(Link)
> Para solicitar o auxilio do PRACTICE entre em contato pelo e-mail practice@uffs.edu.br.

**Comment by CleissonVieira** [comment]
Alterei a última colocação sobre solicitação e visualização das lives já realizadas pelo PRACTICE, pois acredito que são funcionalidades mais utilizadas e requeridas pelo usuário, logo precisa ser de fácil acesso e visualização.
Segue imagens de como ficou:

![image](https://user-images.githubusercontent.com/29258164/99162406-42c80f00-26dc-11eb-9ef6-0fa7ee7e4f03.png)
![image](https://user-images.githubusercontent.com/29258164/99162410-4e1b3a80-26dc-11eb-955d-7b644ec70820.png)
![image](https://user-images.githubusercontent.com/29258164/99162416-58d5cf80-26dc-11eb-8c8a-c67ce3aef268.png)
