### ISSUE TITLE
Solicitação de postagem de material no site do PRACTICE

### ISSUE THREAD

**Issue by thaliafriedrich** [practice-uffs/website-programa#68]
Olá! Criei essa issue para solicitar a postagem de uma cartilha no site do PRACTICE. A cartilha está nomeada como "Dicas para encontrar boas referências bibliográficas" e encontra-se nessa [pasta](https://drive.google.com/drive/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie).
O resumo pode ser o seguinte: Essa cartilha tem como objetivo apresentar algumas dicas e exemplificar um processo de pesquisa e seleção de boas referências bibliográficas, de forma a auxiliar na elaboração de um trabalho acadêmico/científico.

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/99716770-43b7c280-2a87-11eb-8c52-f318139093b4.png)
