### ISSUE TITLE
Solicitação para postagem de cartilha no site do PRACTICE

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/website-programa#69]
A cartilha "Dicas para um melhor aproveitamento das aulas em formato remoto" está finalizada, e encontra-se [nessa pasta](https://drive.google.com/drive/u/0/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie). Portanto, solicito que ela seja postada no site, com o seguinte resumo: 
Participar das aulas em formato remoto, pode parecer um grande desafio para quem nunca vivenciou essa experiência. Sendo assim, elencamos nesta cartilha algumas dicas que podem te auxiliar, tanto no processo de adaptação ao novo formato de ensino, quanto no planejamento e organização dos seus estudos.

**Comment by CleissonVieira** [comment]
Cartilha publicada ao site

![image](https://user-images.githubusercontent.com/29258164/99853604-1429b880-2b62-11eb-9cd3-01e57382baa6.png)
