### ISSUE TITLE
Sugestões de melhorias no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#70]
Revisei o site e vou deixar aqui algumas sugestões de melhorias que possam ser feitas:

- [x] Serviços -> áudio e vídeo -> áudio -> na 3 linha do primeiro parágrafo está escrito ''A nossa equipe de **media** disponibiliza...'' acredito que a palavra correta seria mídia;

- [x] Serviços -> texto e imagem -> paleta de cores -> a imagem referente a paleta de cores do programa está com a qualidade bem baixa, não sendo possível identificar o código das cores, não sei se foi intencional, mas acho que ficaria melhor colocar uma de qualidade superior;

- [x] Sobre -> equipes -> **Ana Carolina Morigi da Cruz Silveira** e **Morgana Maciél Oliveira** estão na equipe de Design Gráfico, porém fazem parte do Auxílio Gerencial mais especificamente da Ger-comunicação. Coloca-las na equipe de Auxílio Gerencial;

- [x] Sobre -> portfólio -> eventos virtuais -> tem a seguinte frase "Nossa equipe utiliza as melhores tecnologias e recursos para enriquecer as transmissões.", acho que seria interessante acrescentar mais informações e imagens a respeito desses recursos visando esse enriquecimento que podem trazer para as transmissões, e na parte de estúdio e vídeo creio que possam ser acrescentadas mais informações a respeito dos possíveis trabalhos realizados;

- [x] Página inicial -> O que é PRACTICE -> linha 3 do terceiro parágrafo -> ''...sem prejuízo, nas atividades **de** envolvam tecnologia.'', acredito que seria ''...sem prejuízo, nas atividades **que** envolvam tecnologia.'';

- [x] Na página inicial temos de cara **O que é PRATICE** que descreve o programa, ao clicar em, Sobre -> **O que é PRACTICE** -> temos a visão geral, e os objetivos do programa, sugiro a mudança de um dos títulos, pois são os mesmo mas com finalidades diferentes. Algumas ideias seriam, Sobre -> **Sobre o PRACTICE/O que buscamos/Objetivos do PRACTICE/Visão geral.**

**Comment by CleissonVieira** [comment]
O último item, como forma de sugestão, solicito a equipe @practice-uffs/con-midia para discutir a respeito. Conversando com @Claudineia-VR foi citado o acréscimo de informações como os diferenciais nas gravações em Eventos virtuais, quais os recursos que o PRACTICE utiliza para esse fim, quais conteúdos deveriam ser acrescentados para instigar o público alvo, etc.

[Clique aqui](https://practice.uffs.cc/portfolio/) para verificar a página a ser analisada e discutida.

**Comment by MaNegrao** [comment]
@luizatonial e @robisonjose podem assumir essa discussão? hehe. Acho que vocês tem muito a contribuir.

**Comment by robisonjose** [comment]
Acredito que só vai ser possível colocar o portfólio em relação aos vídeos quando começarmos a postá-los, não? Mas podemos colocar "Vídeo-aulas", "Adaptação de Cartilhas", "Tutoriais", "Vídeos institucionais", etc. E ai em cada tópico, colocamos alguns exemplos desses materiais produzidos.  

Pra ser sincero, não sei se entendi direito a proposta, mas tentei contribuir.

**Comment by luizatonial** [comment]
Sobre a questão dos eventos virtuais e transmissões ao vivo, tenho impressão de que talvez estas tecnologias estariam ligadas ao estúdio? fiquei na dúvida... no momento estamos fazendo lives utilizando os computadores da universidade remotamente e o @VIF-Franca utiliza no campus.

Não sei o que vocês pretendem divulgar, mas alguns recursos que estamos utilizando no momento nas transmissões ao vivo é a padronização das lives, com o overlay personalizado, que pode ser aplicado para diferentes eventos: somente com apresentador, com slides e também com as intérpretes de libras. O programa que utilizamos é o OBS Studio, conseguimos transmitir qualquer tipo de reunião e conteúdo também, mas estamos priorizando o uso do WebEx, onde conseguimos realizar lives para diferentes oficinas e eventos da UFFS. Um outro recurso que estamos aprimorando é a questão da reprodução do chat do evento na tela da live, que facilita para acompanhar o evento, por exemplo. Além disso teria a questão das capas personalizadas para as lives feitas pelo pessoal do design.

**Comment by MaNegrao** [comment]
Em complemento ao que a luiza e o robison disseram eu tenho pequenos apontamentos.

Na minha visão, quanto aos vídeos a gente pode planejar melhor quando tivermos as issues de mapeamento e de calendario prontas.

Quanto as lives, podemos pegar algumas das informações da pagina de transmissão e colocar nessa página, também.

**Comment by CleissonVieira** [comment]
Gostei muito do que o @robisonjose e @luizatonial comentaram, vou pedir para você (@MaNegrao) com base na [página de Portfólio](https://practice.uffs.cc/portfolio/) atual e no conteúdo citado, montar um novo layout para essa página, de forma que possa ser mais atrativa e tenha mais conteúdo. Como citamos no inicio dessa página no site, daria para informar as tecnologias utilizadas para esta finalidade de lives conforme a Luiza citou, o porque elas são utilizadas, referenciar a cartilha de como realizar lives de qualidade, etc. 

No momento a página só está mostrando uma prévia de algumas lives (sendo possível direcionar para uma página com todas as lives realizadas), algumas frases e 2 imagens.
Quando essa página foi criada não tínhamos muito conteúdo, mas acredito que a realidade é outra nesse momento.

**Comment by MaNegrao** [comment]
Sim, peço perdão ao pessoal pela demora, mas irei montar a página sim e em breve dou continuidade a issue hehe :D

**Comment by MaNegrao** [comment]
@CleissonVieira, @Claudineia-VR @luizatonial e @robisonjose. Eu montei o esquema da pagina como eu imagino por ora, eu gostaria que vocês olhassem e dessem sugestões e correções etc. 

O doc está [aqui ](https://docs.google.com/document/d/1O6sMWi_wmriaPs7ZDnMHwVnyzSCiPHvgIyEXK7q6FN0/edit#)

**Comment by robisonjose** [comment]
Eu achei bem interessante, simples e completo (eu gosto do simples).

**Comment by CleissonVieira** [comment]
Gostei hehehe ficou muito bom!
Vou colocar em prática e repaginar

**Comment by CleissonVieira** [comment]
@MaNegrao no doc que crio não citou sobre essa parte que existe na página de portfolio 

![image](https://user-images.githubusercontent.com/29258164/105665402-bdb85d80-5eb5-11eb-9700-aabb724a80e4.png)

O que me diz, eu mantenho ela no final da página ou elimino?

**Comment by CleissonVieira** [comment]
Páginas reformuladas pessoas. Podem dar uma olhada nos links abaixo:

https://practice.uffs.cc/portfolio/
https://practice.uffs.cc/portfolio/lives/

Obrigado pelo trabalho de todos, ficou muito melhor hehehe <3

**Comment by robisonjose** [comment]
Tem duas coisas que eu não havia notado: 

Tem um "subtítulo" de "Produção de Vídeos" e logo abaixo tem "Gravações em estúdio e vídeos". Não seria melhor deixar apenas "Gravações em estúdio"? 

E a segunda questão é que poderia ser colocado, naquele gif da produção de vídeos, a opção de clicar no gif e levar a pessoa para o vídeo no YouTube.

**Comment by CleissonVieira** [comment]
> Bom dia @CleissonVieira
> 
> Tem duas coisas que eu não havia notado:
> 
> Tem um "subtítulo" de "Produção de Vídeos" e logo abaixo tem "Gravações em estúdio e vídeos". Não seria melhor deixar apenas "Gravações em estúdio"?
> 
> E a segunda questão é que poderia ser colocado, naquele gif da produção de vídeos, a opção de clicar no gif e levar a pessoa para o vídeo no YouTube.

Bom dia @robisonjose 

Ótimas dicas, realizei as alterações. Fiz o mesmo para a primeira imagem com fonte do título "Overlay de transmissões".
Obrigado!
