### ISSUE TITLE
Solicitação de postagem de material no site do PRACTICE

### ISSUE THREAD

**Issue by GessicaZanon** [practice-uffs/website-programa#71]
Essa issue tem como objetivo solicitar a postagem de uma cartilha no site do PRACTICE. A cartilha está denominada "Orientações de uso da Plataforma Moodle" e encontra-se [nessa pasta.](https://drive.google.com/drive/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie)
Quanto ao resumo: Essa cartilha tem como objetivo auxiliar os acadêmicos da UFFS, apresentando orientações de acesso e uso da plataforma Moodle, sistema que é utilizado pela instituição para comunicação entre professores e alunos.

**Comment by CleissonVieira** [comment]
Publicação da cartilha no site concluída.

![image](https://user-images.githubusercontent.com/29258164/105662429-71b5ea80-5eae-11eb-87b2-3272898bee14.png)
