### ISSUE TITLE
Barra de anúncio no topo do site

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/website-programa#73]
Criar uma barra no topo no site (algo como 50px e cor de fundo laranja claro ou coisa parecida), para todas as páginas do site, escrito: "Gostaria de solicitar algum serviço do PRACTICE? Conheça o nosso [mural de solicitações](https://mural.practice.uffs.cc)".

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/113215217-e875b800-9250-11eb-9c70-39b8e0b0be8b.png)

**Comment by Dovyski** [comment]
O aviso está ótimo, @CleissonVieira, só acho que ele precisa ocupar todo o topo do site, antes do bloco do menu. Algo como essa barra do governo federal no site da UFFS:

![image](https://user-images.githubusercontent.com/512405/113303181-346b4000-92d7-11eb-9eba-de9851dd1cb3.png)

**Comment by CleissonVieira** [comment]
Perfeito, vou ajustar então!!

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/113664729-a7333d00-9682-11eb-8104-7a48d50ae01a.png)
