### ISSUE TITLE
Atualização de serviços indisponíveis

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/website-programa#74]
Devido a questões conversadas na reunião de líderes, peço que a equipe @practice-uffs/dev  faça duas alterações no site do PRACTICE:

- [x] Adicionar na página de estúdio que esse serviço está temporariamente indisponível devido a situação da pandemia (adicionar o NSO dos campi);

- [x] Adicionar uma tarja de indisponível nos produtos cartilha e manual da página de texto e imagem.

Se possível, fazer o mesmo no Mural.

**Comment by CleissonVieira** [comment]
@alessandrapedrotti  O que é NSO dos campi?

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti O que é NSO dos campi?

é o nível de segurança operacional; Se for complicado de adicionar isso, basta colocar que os estúdios estão indisponíveis devido a pandemia.

**Comment by oraphaBorges** [comment]
@alessandrapedrotti se for pra deixar algum serviço indisponível no Mural, favor criar uma Issue no projeto do Mural (web-feedback) para registro e histórico.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti se for pra deixar algum serviço indisponível no Mural, favor criar uma Issue no projeto do Mural (web-feedback) para registro e histórico.

@Claudineia-VR podes fazer isso, pfvr?

**Comment by CleissonVieira** [comment]
No website os itens da issue foram implementados. 

Vou aguardar a @Claudineia-VR responder a @alessandrapedrotti e então a Issue pode ser finalizada
