### ISSUE TITLE
Ajustar notícia sobre o feedback dos solicitantes no site

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/website-programa#75]
Esta issue está sendo aberta, de acordo com a issue [522](https://github.com/practice-uffs/programa/issues/522) do repositório programa e conforme a revisão realizada pela equipe responsável pela elaboração do material de divulgação da pesquisa feita sobre o feedback dos solicitantes no PRACTICE. 

Verificamos que alguns trechos na notícia foram retirados, principalmente aos que correspondem a lide (uma frase introdutória que informa o autor sobre do que se trata a notícia, logo abaixo do título) e ao parágrafo correspondente ao contexto em que a pesquisa foi aplicada, estes por sua vez são importantes para manter a coesão do texto e a caracterização do gênero textual. 

Além disso, não é do meu conhecimento e nem da equipe responsável pela elaboração do material, se o site possui um limite de caracteres ou palavras no que diz respeito a publicação de um texto (neste caso a notícia). Caso exista essa limitação, é preciso informar a equipe responsável, para que os ajustes no texto sejam feitos, mantendo-se a coesão e a coerência do mesmo. Situação esta, completamente normal, e que ocorreu por exemplo com os textos que foram publicados no LinkedIn.

Deste modo, peço que ajustem a notícia publicada no site para a sua estrutura original: https://docs.google.com/document/d/1Rk55hfknuCq5JC7q0w-G_CKE1chQzyyFKoyif8ZJXfg/edit (título, lide e corpo da notícia)

E também anexar a imagem com os créditos da equipe responsável pela elaboração do material, que se encontra na pasta: https://drive.google.com/drive/folders/1bPXSn596WRF8ceCUn1C0UOf4-stf0-61

Para quaisquer dúvidas ou eventuais problemas estou à disposição.

**Comment by CleissonVieira** [comment]
Não existem limitações. Foi colocado na notícia do website conforme anexo no momento da issue criada. 
Vou ajustei de acordo com o informado nessa issue.

Uma dica para as próximas imagens de crédito da equipe responsável pela elaboração é criar uma versão com duas colunas de pessoas. A imagem criada para esse eu mantenho para versão mobile (celular) onde não existe largura suficiente para uma imagem com duas colunas. Porém na versão web (notebooks e computadores) eu utilizo essa nova versão onde fica visualmente mais agradável com duas colunas.

Como ficou com a versão atual:

![image](https://user-images.githubusercontent.com/29258164/115155228-5396fb00-a055-11eb-9816-fb761a542f9c.png)
