### ISSUE TITLE
Acrescentar no site: formatos de produtos e direitos autorais

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#76]
Segue abaixo novas informações para o nosso site:

- [x] Informações que falam dos formatos dos produtos do PRACTICE;
Essas informações são referentes a issue [#482](https://github.com/practice-uffs/programa/issues/482) e estão [nesta pasta](https://drive.google.com/drive/folders/1KwFXkGrHEOaNpbIPL6Hhd9dhzXYcMB4U).
- [x] Informações a respeito dos direitos autorais do programa.
Essas informações são referentes a issue [#431](https://github.com/practice-uffs/programa/issues/431) e estão [nesta pasta](https://drive.google.com/drive/folders/1aFndaItVRIiJQebkbEmPnDr8V8JrmQjd).

Qualquer dúvida estou a disposição.

**Comment by CleissonVieira** [comment]
[Página sobre formatos de produtos](https://practice.uffs.cc/servico/formatos/)

[Página sobre direitos autorais](https://practice.uffs.cc/direitos-autorais/)
