### ISSUE TITLE
Inclusão dos nomes e fotos dos novos bolsistas no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#77]
Incluir no site os nomes juntamente com as fotos dos novos bolsistas **dev** no site
- [x] Alisson Luan de Lima Peloso;
- [x] Guilherme Rafael Graeff;
- [x] Stefani Caroline Frare Meneghetti.

As fotos dos bolsistas estão na [pasta de entrada](https://drive.google.com/drive/folders/1uyj4EX_CrCrFLimNU12bdvIMzsGMSsqg) da issue referente a integração dos mesmos ([#533](https://github.com/practice-uffs/programa/issues/533)), outros dados referentes ao novos membros já foram adicionados a [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) no drive.

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/115293747-10f52180-a12e-11eb-821c-dac6ad95a477.png)
