### ISSUE TITLE
Inclusão do nome e foto da nova integrante no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#79]
Incluir no site o nome juntamente com a foto da nova integrante da equipe de con-conteúdo:

Eweline Elen Trojan.

A foto está na [pasta de entrada](https://drive.google.com/drive/folders/1HCe8JyeFz9o7zmy3Dov0ONYn-QbwgxGg) da issue referente a integração da mesma [#584](https://github.com/practice-uffs/programa/issues/584#issuecomment-845975054) outros dados referentes já foram adicionados a [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) no drive.

**Comment by CleissonVieira** [comment]
![Uploading image.png…]()
