### ISSUE TITLE
Incluir novos bolsistas no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#82]
Incluir no site os nomes juntamente com as fotos dos novos bolsistas:
- [x] Adriano Diego Zortea;
- [x] Caroline Balestrini.

As fotos dos bolsistas estão na [pasta da issue](https://drive.google.com/drive/folders/1K1M04shhIzITJngbU0S8LDf46CMF0hkE) referente a integração dos mesmos [(#625)](https://github.com/practice-uffs/programa/issues/625), outros dados referentes ao novos membros já foram adicionados a [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) no drive.

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/122678771-875de080-d1be-11eb-902b-3a30ef94cdb4.png)
![image](https://user-images.githubusercontent.com/29258164/122678779-92187580-d1be-11eb-8f65-ca7ca15be8f7.png)

Concluído
