### ISSUE TITLE
Incluir novos bolsistas no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#85]
Incluir no site os nomes juntamente com as fotos dos novos bolsistas:

- [x] Guilherme Smorcinski Nerling (dev);
- [x] Lucas Frarão (Con-design).

As fotos dos bolsistas estão na [pasta da issue](https://drive.google.com/drive/folders/1IRNSYsfKGRK0DfI0thu128b_d2GmHzGW) referente a integração dos mesmos (#657), outros dados referentes ao novos membros já foram adicionados a [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) no drive.

**Comment by CleissonVieira** [comment]
![image](https://user-images.githubusercontent.com/29258164/124546671-6376dd80-de01-11eb-83db-957942576713.png)
![image](https://user-images.githubusercontent.com/29258164/124546711-6f629f80-de01-11eb-9e9b-2eff39262d6d.png)
