### ISSUE TITLE
Ajuste na aba Direitos Autorais

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/website-programa#88]
Ao final da aba portifólio ajustar links para os dois canais do Practice no Youtube:
Youtube Lives: https://www.youtube.com/channel/UCu3jAl8MTMPkaxb3u0_xESw
Youtube Videos: https://www.youtube.com/channel/UCJZQqcpp1Zzd3eFZhpdzq9Q

**Comment by CleissonVieira** [comment]
@lcaimi acredito que seja apenas na página de Direitos autorais correto? É onde estou realizando as alterações pois identifiquei os links.
Porém no texto dessa issue citou "aba portfólio". Fiquei um pouco confuso
