### ISSUE TITLE
Criar página de política de privacidade

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/website-programa#94]
Se basear no [comentário](https://github.com/practice-uffs/app-practice/issues/159#issuecomment-916003122) para criar a página de privacidade necessária para o lançamento do app.

**Comment by alissonpeloso** [comment]
@CleissonVieira -> PSC

**Comment by alissonpeloso** [comment]
Política de Privacidade -> [privacy.md](https://github.com/practice-uffs/website-programa/files/7137078/privacy.md)

**Comment by CleissonVieira** [comment]
Link para acessar ao termo: <https://practice.uffs.edu.br/termo-politica-privacidade/>

**Comment by Dovyski** [comment]
Eu alterei a url para [https://practice.uffs.edu.br/privacidade/app](https://practice.uffs.edu.br/privacidade/app/)
