### ISSUE TITLE
Atualizações no site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#97]
Incluir no site o nome juntamente com a foto da nova bolsista:
- [x] Vanderléia Pedrotti (con-conteúdo).
A foto está na pasta da issue referente a integração ([#802](https://github.com/practice-uffs/programa/issues/802)), outros dados referentes já foram adicionados a planilha de membros e equipes no drive. **Lembrar de atualizar também o histórico de membros.**

Retirar das equipes do site:
- [x] Jean Carlo Hilger;
- [x] Junior Vitor Ramisch;
- [x] Isabeli Rosana Reik;
- [x] Lucas Frarão.
**Lembrar de atualizar também o histórico de membros.**

Realocar nas equipes:
- [x] Maria Luiza Reviliau, trocar da equipe de design para a equipe de mídia.

Editar:
- [x] Mudar a descrição do curso do Matheus Dias Negrão de ''acadêmico de ciência da computação'' para ''bacharel em ciência da computação'', pois ele já é formado.

**Comment by CleissonVieira** [comment]
Aguardando o servidor atualizar as informações refletindo a adição da Vanderleia no website para finalizar issue

**Comment by Dovyski** [comment]
Rodei a atualização manualmente.
