### ISSUE TITLE
Atualização site

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/website-programa#98]
Incluir no site o nome juntamente com a foto dos novos bolsistas:

- [x] Ana Caroline Geremia (con-mídia);
- [x] Júlia Gaboardi (con-conteúdo);
- [x] Kamila da Rosa (con-design);
- [x] Leonardo Egidio Santin Dall’agnol (con-mídia);

A foto está na pasta da issue referente a integração ([#823](https://github.com/practice-uffs/programa/issues/823)), outros dados referentes já foram adicionados a [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) no drive. Lembrar de atualizar também o histórico de membros.

Colocar novamente no site:
- [x] Isabeli Rosana Reik, como voluntária.
Lembrar de atualizar também o histórico de membros.

Realocar nas equipes:
- [x] Luiz Eduardo Dameda, trocar da equipe de mídia para a equipe de design.

**Comment by CleissonVieira** [comment]
@Claudineia-VR Está faltando as imagens. A pasta referente a integração ([#823](https://github.com/practice-uffs/programa/issues/823)) não possui imagens.
